# Use root/example as user/password credentials
version: '3.1'

services:
  big_ball:
    image: rickychang0118/big-ball:0.0.2
    environment:
      MONGO_URI: mongodb://big_ball_admin:big_ball_admin@mongo:27017/bigball
      COOKIE_KEY: bigball_dev
    ports:
      - 3000:3000
      - 5000:5000
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  cache:
    driver: local